### ISSUE TITLE
Suggestion: additional fields for the User collection

### ISSUE THREAD

**Issue by xlsson** [wadholm/pattern-backend#1]
To accommodate payment functionality, logging in and authentication, and to offer a more realistic admin interface, adding the following fields to the User collection would be useful:

- payment_method (string)
- card_information (string)
- email (string)
- password (string)
- surname (string)
- phone (string)

**Comment by wadholm** [comment]
From a UX-perspective, which of these fields needs to be required? Can email and password be required if user is signed in with OAuth?

**Comment by xlsson** [comment]
Good question. UX-wise, as few required fields as possible, is the way to go, perhaps? My understanding is that for OAuth, we would need the email field, but not the password field? If we want to offer an alternative way to log in, we could require the password field to be filled out in the actual user interface, and not in the database.

> Kunden kan fylla på med pengar till sitt konto (prepaid), eller låta systemet dra
> pengar varje månad via en betalningstjänst.

Since customers can choose between prepaid or subscription, card_information should perhaps also be possible to leave empty in the database. payment_method can really only contain two different values (prepaid/subscription) = could be a required field, with "prepaid" as a default value? Do any other fields need to be required?
