### ISSUE TITLE
Förslag: "name"-fält för charge_stations och parking_stations

### ISSUE THREAD

**Issue by xlsson** [wadholm/pattern-backend#3]
![image](https://user-images.githubusercontent.com/71336413/144901836-61574ebb-d91a-4142-8056-1db16965aaff.png)

Jag tycker det vore kanon med ett "name"-fält för båda dessa, så att man t.ex. kan visa upp "Stora Torget" eller liknande istället för ett långt id i dropdowns och i laddnings-/parkeringsstationsöversikterna. Det behöver kanske inte nödvändigtvis vara ett unikt fält (även om det såklart blir krångligt om företaget väljer att kalla alla sina laddningsstationer för samma sak).

**Comment by wadholm** [comment]
Det låter som en bra idé, jag vet inte exakt hur det fungerar med unika fält i sub-dokument om de endast är unika per dokument då kanske, jag ska läsa på lite om det och implementerar den lösningen som blir bäst. Det vore ju bra om olika städer kan döpa sina stationer till samma namn (typ "Stora Torget"), men namnen borde nog vara unika per stad annars gör det sig inte jättebra i en dropdown heller? Om det inte går att få till i databasen så får man ju bara se till annars att inte döpa stationer i samma stad till samma namn? Kanske inte den mest optimala lösningen men för vårt lilla projekt kan det kanske vara gott nog.

**Comment by xlsson** [comment]
OK :) Det är nog gott nog! Man skulle kunna argumentera för att företaget inte har så överdrivet många laddningsstationer i en stad, och att de mer eller mindre "av naturen" låter bli att namnge dem likadant.
