### ISSUE TITLE
Datatyper i Bikes

### ISSUE THREAD

**Issue by xlsson** [wadholm/pattern-backend#4]
När man skapar en cykel blir coordinates.lat och coordinates.long Int32 (d.v.s. heltal), men för att kunna hantera flyttal skulle datatypen behöva vara Double.

"battery_status" skulle behöva ha ett heltal som utgångsvärde (kanske 100 = fullt batteri?), och smidigast vore kanske att ändra datatypen till Int32?

![image](https://user-images.githubusercontent.com/71336413/144902948-c78e7210-ff41-4957-abb4-dd20bf108e35.png)

**Comment by wadholm** [comment]
Cykelns koordinater är bara default-värden, det går inte att tvinga default 0.0, koordinaterna för cykeln kan hantera float, det är bara att uppdatera dem med riktiga koordinater. I MongoDB likt JS används typen Number som kan hantera både int och float. Det är samma sak som när vi diskuterade datatypen för de övriga koordinaterna, jag kan försöka implementera någon extra validator för att endast float ska fungera, frågan är om det verkligen behövs?
Jag ändrar datatypen för batteristatus till Number med default 100.

**Comment by xlsson** [comment]
Ah! Då är jag med :) Jag trodde att datatypen var spikad och klar till det man såg i Atlas, men då drar jag mig tillbaka till under den sten jag kom ifrån. Sorry! Nej, då tror inte jag heller någon validering behövs.

**Comment by wadholm** [comment]
Haha nej det är ingen fara, det är inte helt lätt att förstå alla MongoDB nycker, jag gör det absolut inte! :)
Jag kan också ta bort default-värdet från cykeln om vi vill? Är mest att jag gillar default-värden när jag testar mig fram, så att man kan visualisera datan utan att ha några riktiga värden, if that makes any sence..
