### ISSUE TITLE
Utmaning: Underhåll, laddning och bike_status

### ISSUE THREAD

**Issue by xlsson** [wadholm/pattern-backend#5]
Jag funderar lite på det här med maintenance och laddning. Här är ett screenshot från kravspecifikationen:

![image](https://user-images.githubusercontent.com/71336413/144904274-d0d1892a-cafd-4181-89cb-eb7a250e9440.png)

Som jag tolkar kravet så skulle cykeln faktiskt behöva bli oanvändbar ett tag, under underhållet/laddningen. Kanske är det ändå läge att försöka implementera den lite krångligare versionen av underhåll (som vi tog med i use-caset i SDS:en men som vi lade på is tills vidare)? Samma princip skulle man kanske kunna använda för laddning.

Hur ser ni på det? Har vi t.ex. kommit alltför långt i serverkodandet / Pythonprogrammet / kundens gränssnitt/app, för att det ska vara möjligt att göra en sådan ändring?

Här är ett förslag på hur man skulle kunna göra det:

- Både laddning och underhåll sker endast på laddningsstationerna
- Två nya fält skulle behövas: "maintenance" och "charging", med timestamp som datatyp (eller motsvarande i MongoDB)
- Om cykeln parkeras inom koordinaterna för en laddningsstation så sätts "battery_status" direkt till 100, och "charging"-fältet sätts till aktuell tidpunkt.
- Om en admin bestämmer att cykeln är i behov av underhåll så sätts aktuell tidpunkt i "maintenance"-fältet
- Vi bestämmer en fast tid som ska gälla för hur länge underhåll (kanske 24 timmar?) respektive laddning (kanske 3 timmar?)
- I kundens app och admingränssnittet tolkar cyklar med "maintenance" yngre än 24 timmar och "charging" yngre än 3 timmar som ej tillgängliga.
- Kriteriet att "maintenance" och "charging" har timestamps som är äldre än 24 resp. 3 timmar (eller att de är tomma), skulle alltså behöva uppfyllas för att man ska kunna hyra cykeln.

Att implementera detta skulle alltså innebära att skapa två nya fält, och att i våra gränssnitt ändra kriterierna för när en cykel anses vara möjlig att hyra.

Är det vettigt, är det nödvändigt och vore det rimligt och möjligt att genomföra? 

![image](https://user-images.githubusercontent.com/71336413/144903404-59c75cfd-b666-4662-b250-7eef6e8efb5a.png)

Fältet bike_status skulle kunna bytas ut mot ett boolean-fält (kanske med namnet "free"), som endast markerar om cykeln just nu hyrs av någon eller inte.

**Comment by xlsson** [comment]
....maintenance skulle iofs kunna lösas genom att en admin bara bestämmer att en cykel nu är lagad = underhållet är slut. Så där kanske det egentligen räcker med en boolean, och inget krångel med timestamps. 

Men hur ser vi på laddningen?

**Comment by xlsson** [comment]
Sammanfattning från morgonmötet: diskussion om laddning och underhåll:

En bättre idé än att jobba med timestamps är att låta servern arbeta med en timeout. På så vis behöver inte gränssnitten hålla koll på timestamps för att avgöra en cykels status, d.v.s. mindre logik i gränssnitten och mer på servern. Vi slipper också lägga till de fält som hade krävts för timestamp-värdena.

Laddningen sker genom att en anställd byter ut cykelns batteri mot ett nytt. Därmed tar laddningen alltid lika lång tid, och går mycket fortare än vi ursprungligen tänkt. Cirka 10 minuter är en rimlig tid.

**Laddning**:

- En cykel kan hamna på en laddningsstation av två anledningar:
antingen genom att en admin beställer hämtning dit via admingränssnittet, eller att en kund avslutar resan där. 

- I båda fallen skickar respektive subsystem (admingränssnitt resp. cykelns program) en request till servern, med fältet "charge_id" satt till id:t för aktuell laddningsstation.

- När servern tar emot requestet sker följande:
Cykelns "bike_status" sätts till "unavailable".
En timeout sätts, som efter t.ex. 10 minuter sätter "bike_status" till "free" och "battery_status" till 100. 


**Start av underhåll** (som automatiskt även inkluderar laddning):

- Vid beställning av hämtning till en laddningsstation har en admin möjlighet att även begära underhåll genom sätta fältet "maintenance" till true. Bedömningen om när underhåll behövs görs av admin själv, och sker inte per automatik.

- En request, över en maintenance-route, skickas till servern, med fältet "charge_id" satt till id:t för aktuell laddningsstation, samt fältet maintenance satt till "true". På servern sker följande:
Cykelns "bike_status" sätts till "unavailable".

**Slut av underhåll**:

- När en admin bedömer att underhållet är klart kan "maintenance" sättas till true i admingränssnittet.

- En request, över en maintenance-route, skickas till servern, med fältet "charge_id" satt till id:t för aktuell laddningsstation, samt fältet maintenance satt till "false". På servern sker följande:
Cykelns "bike_status" sätts till "free"  och "battery_status" till 100.

**To-do**:
Ett "maintenance"-fält (boolean) skulle behöva läggas till.
En route för maintenance behöver tillkomma.
Servern behöver kunna hantera ovan nämnda logik.
Gränssnitten behöver anpassas för att hantera ovan nämnda logik.

**Comment by wadholm** [comment]
Hur håller vi ner antalet beslutspunkter och skriver "snygg" kod? Ett alternativ är att ha en funktion i cykel-controllern med en beslutspunkt om cykeln ska underhållas eller är färdig, alternativt en varsin funktion typ set_maintanance och unset_maintanance. Det jag funderar över är "good and clean code" som ändå verkar vara en viktig och väsentlig del för Mikael när projektet ska betygsättas. Med ovan lösning skapar vi både beslutspunkter och fler funktioner,  när vi egentligen redan har en funktion som kan uppdatera valfria fält i en cykel. Routen för att uppdatera cykeln kan ju göra allt vi vill ska hända när en cykel ska underhållas eller inte, det handlar ju bara om att skicka med "rätt" data. Min fundering är nog vad fördelen är att skapa många olika routes  och funktioner? 

@xlsson: Problemet jag såg framför mig var:
- När en kund avslutar resan på en laddningsstation kommer det in en request med bl.a. "charge_id" satt till laddningsstationens id, samt "maintenance" satt till false. Det triggar då laddning i 10 minuter.
- När en admin bedömer att underhållet är över kommer det in en identisk request, d.v.s. med  "charge_id" satt till laddningsstationens id, samt "maintenance" satt till false.

Men med PATCH skulle man kunna strunta i att överhuvudtaget skicka med "maintenance"-attributet när kunden avslutar resan?

**Comment by xlsson** [comment]
wadholm skrev:
_Nu finns en uppdaterad version av repot, jag har inte lagt till några routes utan använder PATCH http://localhost:1337/bikes/:cykelid. För laddning av cyklar finns nu en setTimeout(satt till 1 min och inte 10 nu vid testning). Om en cykel uppdateras med ett charge_id och ett batterivärde som är lägre än 20(testvärde), uppdateras dess bike_status till "unavailable" och efter 1 min uppdateras cykeln i databasen till bike_status "available" och battery_status 100. För maintenance har jag gjort att man tex via admin-gränssnittet skickar med en array likt:_

```
[
    {"propName": "maintenance", "value": true},
    {"propName": "bike_status", "value": "unavailable"}
]
```

och när maintenance ska avslutas skickas istället:

```
[
    {"propName": "maintenance", "value": false},
    {"propName": "bike_status", "value": "available"},
    {"propName": "battery_status", "value": 100}
]
```

**Comment by xlsson** [comment]
Vore det också ett alternativ att en cykel alltid laddas när den landar på en laddningsstation, oavsett batterinivå? Jag tänker att elsparkcykelföretaget borde ha ett intresse av att cyklarna alltid är så laddade som möjligt. Och så kanske koden t.o.m. blir smidigare.

**Comment by xlsson** [comment]
Snyggt jobbat med setTimeout, och bra idé av @richardstg!

Jag upptäckte ett problem som uppstår när en admin skickar cykeln till en laddningsstation och samtidigt väljer att den ska genomgå underhåll. Efter 1 minut är laddningen klar, och då sätts cykeln som "available", trots att underhållet ännu inte är klart.  I ett sådant läge ska ju cykeln ännu inte kunna hyras. Först när admin sätter "maintenance" till false igen ska det gå. Vad vore det smidigaste sättet att lösa detta på?

Kan man lösa det med ett if-villkor i chargeBike(), som kollar om "maintenance" är true/false, och endast sätter "bike_status" till "available" om "maintenance" är false?

**Comment by wadholm** [comment]
Det är väl en riskbedömning om batteriet slits ut i förtid om det laddas ofta och batteriet inte hinner laddas ur emellanåt men det borde ju inte vara ett problem för våra cyklar direkt så det fungerar för min del. Vad tror vi om att setTimeout-laddningen bara triggas om cykeln inte är bokad för underhåll? Om cykeln skall underhållas så "laddas" batteriet manuellt när den är klar med underhållet likt exemplet för att avsluta maintenance ovan?  Det blir dock väldigt många beslutspunkter, jag ska fundera på om jag måste tänka om i strukturen för just laddning och underhåll.

**Comment by wadholm** [comment]
Nu ska problemet vara löst, jag har inte ändrat villkoren för batteriladdning ännu.

**Comment by xlsson** [comment]
Bra poäng med att batteriet kan slitas, det kanske är bra att ha det villkoret kvar (och vill vi ändra det längre fram så är det ju bara att ändra på gränsen för när batteriet ska laddas).

Om man villkorar setTimeout-laddning med om cykeln bokas för underhåll skulle följande kunna hända tänker jag:
- Cykel står på en laddningsstation och har påbörjat laddning
- Admin beställer därefter underhåll
- Cykeln laddas klart, och "bike_status" sätts automatiskt till "available", innan underhållet är klart

**Comment by wadholm** [comment]
Jag testar en annan lösning, mer som vi tänkte i början. Laddning av cykel görs som "vanligt" med att cykeln hamnar på en laddstation och batteriet är mindre än ett visst värde. När admin bokar underhåll för en cykel görs det via en egen route: 

`router.put('/maintenance/:bikeId', BikesController.bikes_maintenance);`

För att starta underhåll skickas liknande exempel: 
```
{
    "maintenance": true,
    "charge_id": "61a93c3ce146af1a898bdb34"
}
```
För att avsluta underhåll:
```
 {
    "maintenance": false
}
```

Det kan ju dock fortfarande bli problem om en cykel laddas och admin bokar underhåll under tiden cykeln laddas men jag vet inte riktigt hur vi ska komma runt det, jag kan inte komma på hur man tex skulle kunna använda clearTimeout om man inte ska spara timeoutID i databasen.

**Comment by xlsson** [comment]
Ett if-villkor i chargeBike(), som kollar om "maintenance" är true/false, och endast sätter "bike_status" till "available" om "maintenance" är false vore kanske en lösning (men det innebär ju en förfrågan till databasen - men det kanske är svårt att undvika..).

**Comment by wadholm** [comment]
Det känns svårt att undvika, jag har gjort en sån lösning nu, koden känns kanske inte optimal, ni får gärna komma med förbättringsförlag på update_bike och chargeBike om ni kommer på något men nu verkar det fungera.

**Comment by wadholm** [comment]
Senaste ändringarna är pushade.

**Comment by xlsson** [comment]
Gött! Har uppdaterat admingränssnittet, och det verkar funka.
