### ISSUE TITLE
Förslag: stad för användare i user collection

### ISSUE THREAD

**Issue by richardstg** [wadholm/pattern-backend#6]
Efterfrågar att användaren ska ha en stad kopplad till sig för att på så vis kunna använda denna som default i appen.

**Comment by xlsson** [comment]
Tänker vi att kunder ändå kommer att kunna hyra cyklar i alla städer? D.v.s. staden blir "favoritstaden", och påverkar egentligen endast vilken stad som visas i appen?

**Comment by richardstg** [comment]
Ja, det är endast för att kunna ha en default-stad när appen används.

**Comment by wadholm** [comment]
Är tanken att en användare ska ange stad vid registrering eller något som man uppdaterar efter att en användare är skapad?

**Comment by richardstg** [comment]
Tänkte först och främst att det är något användaren kan ange i sitt webbgränssnitt, efter man skapat en användare.

**Comment by xlsson** [comment]
Om vi inför detta så lägger jag även till det som ett fält som en admin kan ändra hos en kund.

**Comment by wadholm** [comment]
Nu är city tillagt i user-modellen och ändringarna är pushade. Ni får gärna testa att det fungerar som tänkt så kan vi stänga denna issuen?

**Comment by xlsson** [comment]
Jag tänker att propertyn nog behöver läggas till redan vid registrering, så att man kommer åt propertyn user.city, annars blir det "undefined property" (eller liknande fel)  t.ex. när användarens info ska läsas in i admingränssnittet. Propertyn skulle kunna vara tom, men den skulle nog behöva finnas.

**Comment by xlsson** [comment]
Raderade min kommentar om att city-propertyn behöver finns med från början - verkar funka ändå!

**Comment by xlsson** [comment]
Verkar även gå fint att uppdatera med PATCH.
