### ISSUE TITLE
users/register - firstname vs firstName

### ISSUE THREAD

**Issue by xlsson** [wadholm/pattern-backend#7]
När jag testade att regga en ny användare märkte jag att servern vill ha firstName och lastName, och inte firstname och lastname. Det senare stämmer väl bättre överens med hur de kallas på andra ställen, så kanske smidigast att ändra till det (med brasklapp för om jag missat nåt)?

**Comment by wadholm** [comment]
Det är ett slarvfel från mig, jag fixar!
